name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  nix-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v27

      - name: Enter Nix shell and run tests
        run: |
          nix develop --command bash
        shell: bash

      - name: Run tests inside Nix shell
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          make clean && make
          make embedding-server &
          sleep 10
          bash scripts/test_embedding_pipeline.sh
          bash scripts/test_ci.sh
        shell: nix develop --command bash
