name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  nix-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
      - name: Enter Nix shell and run tests
        run: |
          nix develop --command bash -c '
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            make clean && make
            make embedding-server &
            sleep 10  # Give server time to start
            bash scripts/test_embedding_pipeline.sh
            bash scripts/test_ci.sh
          '

  macos-homebrew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew dependencies
        run: |
          brew install cpr llvm nlohmann-json
      - name: Debug: Show working directory and files
        run: |
          pwd
          ls -l
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up venv and install Python deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Build and test
        run: |
          source venv/bin/activate
          make clean && make
          make embedding-server &
          sleep 10
          bash scripts/test_embedding_pipeline.sh
          bash scripts/test_ci.sh