name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-nix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build with Nix
      run: nix build
    
    - name: Run tests with Nix
      run: nix flake check
    
    - name: Test development shell
      run: nix develop --command bash -c "make clean && make && echo 'help' | timeout 5s ./mimir || true"

  build-ubuntu-traditional:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
    
    - name: Build and test
      run: |
        chmod +x scripts/*.sh
        ./scripts/setup_env.sh
        ./scripts/build.sh
        ./scripts/test_ci.sh

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build with Nix
      run: nix build
    
    - name: Test with Nix
      run: nix develop --command bash -c "make clean && make && echo 'help' | timeout 5s ./mimir || true"