name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
    
    - name: Setup environment
      run: |
        chmod +x scripts/setup_env.sh
        ./scripts/setup_env.sh
    
    - name: Build project
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
    
    - name: Run CI tests
      run: |
        chmod +x scripts/test_ci.sh
        ./scripts/test_ci.sh

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (macOS)
      run: |
        # Install coreutils for gtimeout
        brew install coreutils
    
    - name: Setup environment
      run: |
        chmod +x scripts/setup_env.sh
        ./scripts/setup_env.sh
    
    - name: Build project
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
    
    - name: Run CI tests
      run: |
        chmod +x scripts/test_ci.sh
        ./scripts/test_ci.sh

  test-workflow:
    runs-on: ubuntu-latest
    needs: build-ubuntu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
    
    - name: Setup and test workflow
      run: |
        chmod +x scripts/*.sh
        ./scripts/setup_env.sh
        ./scripts/test_workflow.sh